### ISSUE TITLE
Contraste

### ISSUE THREAD

**Issue by SakuraBravo** [SakuraBravo/cdmx-2018-06-bc-core-am-data-dashboard#10]
Comentario de Amalia:

> Contraste: Comienzan a hacer uso del contraste en colores de fondo y texto, considero que pueden ir algunos pasos más allá en la experimentación del contraste en títulos y colores de texto de los distintos componentes visuales que manejan. Para que en la composición también se vaya incluyendo el concepto de

**Comment by ninagallo** [comment]
Realizar cambios de barra, saku ancho en desktop antes de hacer pull request.
Edito CSS para contraste en la barra de navegacion:

Bloque izq. en color rosa o verde laboratoria
Hover: Ver que color contrasta mejor.
Active: que permanezca el color de hover
