### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by SakuraBravo** [SakuraBravo/cdmx-2018-06-bc-core-am-data-dashboard#12]
Comentario de Amalia:

> Color: Se cambian los colores por default eso es un buen primer paso, la idea es usar un número determinado de colores que acompañen la composición a lo largo de los componentes. De ser el caso, utilizar los colores y variaciones de color del manual de la marca con la que se está trabajando.

**Comment by ninagallo** [comment]
Saku, lo voy a trabajar con la edicion de los colores de la sidebar. 
No hay monitos  👍 retiro lo dicho, si hay.

**Comment by SakuraBravo** [comment]
si hay monitos 💃
