### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by SakuraBravo** [SakuraBravo/cdmx-2018-06-bc-core-am-data-dashboard#9]
Comentario de Amalia:

> UX: Entrevistas, documentemos grabaciones de audio y video!

Documentar todo la investigación de Research que se hizo.

- [x] Link de protocolo de entrevista

- [ ] Link de entrevista en audio a Mike

- [ ] Link de entrevista en audio a Andy

- [ ] Link de entrevista en video a Lucile 

- [x] Documento de test de Usabilidad de Lucile o Audio.

**Comment by ninagallo** [comment]
Oki
